### ISSUE TITLE
Upload script does not with Python 3.7

### ISSUE THREAD

**Issue by ojwoodford** [intel-isl/TanksAndTemples#24]
I've tried to use Python 3.7 to upload my results (Intermediate sets only) for evaluation. However, the script throws two errors. If I change line 146 to `md5_check = open(md5_check_fn, 'w')`, and lines 153 & 157 to `md5_ply_file = b''`, the errors are fixed. However, when I then upload my results, the server complains that the MD5 checksums are wrong.

The only way I've been able to upload the results with correct MD5 checksums is to use the original script with Python 2.7.

**Comment by syncle** [comment]
Resolved with #25. Thanks, @ojwoodford and @arknapit!
