### ISSUE TITLE
Why is the uploading slow sometimes?

### ISSUE THREAD

**Issue by TruongKhang** [intel-isl/TanksAndTemples#33]
Hi,

I'm submitting the results to your benchmark websites. The first time is fast. But in next time, the uploading is very slow. It takes several hours.
Do you know any problems here?

Thank you.
Khang.

**Comment by doubleZ0108** [comment]
I think this problem also hit me, so have you figure out what is the problem?
My `.ply` is more than 40G, so it is really a long way for me to submit each files.

**Comment by arknapit** [comment]
> so it is really a long way for me to submit each file.

can you specify what the exact problem is? Does it break at some point or is the md5 incorrect after the upload? Although 40G shouldnt be a problem in the upload, we have seen that even very densely sampled plys are usually just 2-3GB, and the rest of the pointcloud is from the reconstruction outside the object ROI (e.g. background/noise) - so if you can crop your plys to the rough boundaries of the object already, you can speed up the upload by a large factor.

**Comment by doubleZ0108** [comment]
Really thanks for your reply, I made a mistake for taking `14G` into `40G`, please forgive this.
The md5 check just correct, I think maybe due to my poor network connection.
Locate in China mainland is sometime low speed for the connection to your server.
